# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d63c4d3a8485d9756f48e4c05c39ad405e2a0e947354cf20eb8177f4121757e93523859e8e1c39a465a95a3905c0ec54d14ea44792a238f10a4be1a3ce95aea

test:
  secret_key_base: 3f4f6bbc264a3d8bc7b16e4fd606364cc44051d4219afa6c2fcaf1cce98cd681c597138253884cba12506e2eeeec33dd8c953d675ab6427b73b4d928c4a06b1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
